version: '3'

services: 
  api:
    build: .
    command: yarn dev
    links: 
      - mongo
    depends_on: 
      - mongo
    ports: 
      - "${PORT}:5000"
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
  mongo:
    restart: always 
    image: mongo:4.2.9-bionic
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - ./mongo:/data/db